### ISSUE TITLE
Install - requirements.txt changes

### ISSUE THREAD

**Issue by jboyd79** [virajkothari7/OnlineRetailPOS#3]
Hello Viraj,

Thanks for very much for this django app. I just installed it on Ubuntu 22.04.1 and it works and looks great!

I did get some error messages with the install regarding mysql client, numpy and psycopg2.
I removed mysqlclient, changed psycopg2 to psycopg2-binary, and downgraded numpy to numpy==1.26.4 and everything seems to be working.

I also made a change to the transactions.view and got a network printer working.
If you are willing, I do have some questions for you.

Best Regards,
John.

**Comment by virajkothari7** [comment]
You only need mysqlclient if you are using mysql as database, since you were able to tweak and get it working that sounds good. 

Yeah I guess you can integrate network printer but that would only be access from network where your Django app is running. I wanted to set printer through front end, I don't think I was able to achieve that so I just put in the method on server side. 

Sure, what are your questions?

**Comment by jboyd79** [comment]
Hi Viraj, Thanks for the reply.

No more questions yet. Still exploring the app.
Will update you as I go along.

Best Regards.
John.
