### ISSUE TITLE
Deposits Model

### ISSUE THREAD

**Issue by jboyd79** [virajkothari7/OnlineRetailPOS#4]
Hello Viraj,

Does the Deposits model refer to Bank deposits? 
I cannot figure out the exact purpose and use of the Deposit model.
I would be most thankful if you can elaborate on this.

Best Regards,
John.

**Comment by virajkothari7** [comment]
deposit model in inventory is for bottle deposit, usually in some places they charge deposit on bottles/cans. For example, on can of soda they would add tax and deposit on price since they are required to collect deposit on recyclable cans/bottle.

You can try searching for bottle deposit for better understanding.

**Comment by jboyd79** [comment]
Thanks!
